sudo: false
language: ruby
cache:
  directories:
    - vendor/bundle
    - node_modules
install:
  - bundle install --deployment --jobs=3 --retry=3
  - npm install -g grunt-cli
  - npm install
script:
  - grunt build
after_success:
  - tools/auto-deploy.sh

